export const motherTongues = [
  "Hindi",
  "Marathi",
  "Gujarati",
  "Telugu",
  "Tamil",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Bengali",
  "Urdu",
  "Odia",
  "Assamese",
  "English",
  "Other",
];

export const religions = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Jain",
  "Buddhist",
  "Parsi",
  "Jewish",
  "Other",
];

export const castesByLanguage = {
  Hindi: [
    "Brahmin",
    "Rajput",
    "Baniya",
    "Agarwal",
    "Gupta",
    "Jat",
    "Yadav",
    "Kayastha",
    "Khatri",
    "Thakur",
    "Vaishya",
    "Kurmi",
    "Patel",
    "Marwari",
    "Bhumihar",
    "Tyagi",
    "Saini",
    "Gujjar",
    "Ahir",
    "Lodhi",
    "Chamar",
    "Kumhar",
    "Teli",
    "Sahu",
    "Sunar",
    "Verma",
    "Sharma",
  ],
  Marathi: [
    "Maratha",
    "Brahmin (Deshastha)",
    "Brahmin (Kokanastha)",
    "Brahmin (Saraswat)",
    "Brahmin (Karhade)",
    "Kunbi",
    "Mahar",
    "Mali",
    "Dhangar",
    "Shimpi",
    "Sonar",
    "Teli",
    "Agri",
    "Koli",
    "Bhandari",
    "Lingayat",
    "Gurav",
    "Sutar",
    "Lohar",
    "Chambhar",
    "Nhavi",
    "Deshmukh",
    "Patil",
    "CKP (Chandraseniya Kayastha Prabhu)",
    "Matang",
    "Vani",
  ],
  Gujarati: [
    "Patel (Leuva)",
    "Patel (Kadva)",
    "Brahmin (Audichya)",
    "Brahmin (Nagar)",
    "Brahmin (Anavil)",
    "Baniya / Vaishnav",
    "Rajput / Kshatriya",
    "Lohana",
    "Jain (Digambar)",
    "Jain (Shwetambar)",
    "Koli",
    "Darbar",
    "Mochi",
    "Suthar",
    "Rabari",
    "Ahir",
    "Vaniya",
    "Bhatia",
    "Sindhi",
    "Panchal",
    "Soni",
  ],
  Telugu: [
    "Reddy",
    "Kamma",
    "Kapu",
    "Brahmin (Niyogi)",
    "Brahmin (Vaidiki)",
    "Velama",
    "Naidu",
    "Raju / Kshatriya",
    "Arya Vysya",
    "Yadav / Golla",
    "Balija",
    "Mala",
    "Madiga",
    "Padmashali",
    "Goud",
    "Mudiraj",
    "Munnuru Kapu",
    "Mangali",
    "Chakali",
    "Setti Balija",
    "Boya",
    "Kurma",
  ],
  Tamil: [
    "Brahmin (Iyer)",
    "Brahmin (Iyengar)",
    "Mudaliar",
    "Gounder (Kongu Vellalar)",
    "Nadar",
    "Thevar / Mukkulathor",
    "Maravar",
    "Kallar",
    "Agamudayar",
    "Chettiar",
    "Vanniyar",
    "Pillai",
    "Naicker",
    "Adi Dravida",
    "Paraiyar",
    "Devendra Kula Vellalar",
    "Senguntha Mudaliar",
    "Udayar",
    "Yadava",
    "Vishwakarma",
    "Sourashtra",
    "Reddiar",
  ],
  Kannada: [
    "Lingayat / Veerashaiva",
    "Vokkaliga (Gowda)",
    "Brahmin (Smartha)",
    "Brahmin (Madhwa)",
    "Brahmin (Havyaka)",
    "Kuruba",
    "Bunt / Shetty",
    "Billava",
    "Devanga",
    "Adi Karnataka",
    "Idiga",
    "Ganiga",
    "Jain",
    "Madivala",
    "Tigala",
    "Mogaveera",
    "Nayaka",
    "Ediga",
    "Badaga",
    "Kodava",
  ],
  Malayalam: [
    "Nair",
    "Ezhava",
    "Thiyya",
    "Brahmin (Namboothiri)",
    "Brahmin (Embrandiri)",
    "Syrian Christian",
    "Latin Catholic",
    "Menon",
    "Kurup",
    "Pillai",
    "Mapilla",
    "Pulaya",
    "Nambiar",
    "Vishwakarma",
    "Warrier",
    "Ambalavasi",
    "Dheevara",
  ],
  Punjabi: [
    "Jat Sikh",
    "Khatri",
    "Arora",
    "Ramgarhia",
    "Rajput",
    "Saini",
    "Ahluwalia",
    "Gujjar",
    "Tarkhan",
    "Bhatia",
    "Lubana",
    "Brahmin",
    "Mazhabi Sikh",
    "Ramdasia",
    "Kamboj",
    "Ravidasia",
    "Sunar",
  ],
  Bengali: [
    "Brahmin (Kulin)",
    "Brahmin (Baidik)",
    "Kayastha",
    "Baidya",
    "Mahishya",
    "Namasudra",
    "Sadgop",
    "Teli",
    "Subarnabanik",
    "Gandhabanik",
    "Rajbanshi",
    "Pod / Poundra",
    "Bagdi",
    "Kaibarta",
    "Suri",
    "Tambuli",
    "Aguri",
    "Karmakar",
    "Saha",
  ],
  Urdu: [
    "Syed",
    "Sheikh",
    "Pathan",
    "Mughal",
    "Ansari",
    "Qureshi",
    "Khan",
    "Malik",
    "Mirza",
    "Hashmi",
    "Siddiqui",
    "Faruqi",
    "Abbasi",
    "Alvi",
    "Rizvi",
    "Baig",
    "Bohra",
    "Memon",
    "Mansoori",
  ],
  Odia: [
    "Brahmin",
    "Khandayat",
    "Karana",
    "Chasa",
    "Gouda",
    "Teli",
    "Sundhi",
    "Pana",
    "Dhoba",
    "Bauri",
    "Gokha",
    "Keuta",
    "Patra",
    "Gudia",
  ],
  Assamese: [
    "Brahmin",
    "Kalita",
    "Kayastha",
    "Koch",
    "Ahom",
    "Chutia",
    "Keot",
    "Nath / Yogi",
    "Bodo",
    "Mishing",
  ],
  English: [
    "Anglo-Indian",
    "Christian",
    "Catholic",
    "Protestant",
    "Other",
  ],
  Other: [
    "Brahmin",
    "Kshatriya",
    "Vaishya",
    "Other",
  ],
};

// All unique castes combined for fallback or open search
export const allCommonCastes = Array.from(
  new Set(Object.values(castesByLanguage).flat())
).sort();

export const getCastesForLanguage = (language, includeNoPreference = true) => {
  const languageCastes = language && castesByLanguage[language]
    ? castesByLanguage[language]
    : allCommonCastes;

  if (includeNoPreference) {
    return ["No Preference", ...languageCastes];
  }
  return languageCastes;
};
